### ISSUE TITLE
Travis Failing

### ISSUE THREAD

**Issue by vinkla** [vinkla/dotfiles#1]
Travis keep failing and it can't seem to install `brew`. 

@mikemcquaid, the tested script is taken from your Strap repository. Have you encountered this before?

https://travis-ci.org/vinkla/dotfiles/builds/81336811

```bash
The command "STRAP_CI=1 STRAP_DEBUG=1 ./bin/setup.sh" exited with 126.
$ brew install --build-from-source etl
/Users/travis/build.sh: line 41: brew: command not found

The command "brew install --build-from-source etl" exited with 127.
$ brew cask install flux
/Users/travis/build.sh: line 41: brew: command not found

The command "brew cask install flux" exited with 127.
$ brew install checkbashisms
/Users/travis/build.sh: line 41: brew: command not found

The command "brew install checkbashisms" exited with 127.
$ checkbashisms --posix --
```

**Comment by mikemcquaid** [comment]
It's not running your `setup.sh` because it's not executable.

**Comment by vinkla** [comment]
Aah I see, thanks for responding! I'll try it out.

**Comment by vinkla** [comment]
Btw, is the copyright and license okay? I've added your repo to the description. Do you want me to keep your license as well?

**Comment by mikemcquaid** [comment]
Ideally you'd separate `strap.sh` into a separate file and state that it's copyright me and under the MIT license but you're entitled to do whatever you want as long as it complies with the MIT license :smile:

**Comment by vinkla** [comment]
Okay, I really want to keep it in the same file but what if I mention you in the script? I've to read up on the MIT license to see what is necessary to add :smile:

**Comment by mikemcquaid** [comment]
Yeh, that's fine. You may have problems importing new versions though. Might not be a bad idea to just have `setup.sh` call `strap.sh` and then call `vinkla.sh` or wherever you want to keep your person customisations. Whatever you prefer, though!

**Comment by vinkla** [comment]
How do you mean? You mean new versions of the `strap.sh` script? I'm going to be a dedicated follower of your commit history :)

**Comment by mikemcquaid** [comment]
Yeh, newer versions. I just mean if it's a separate file you can copy and paste it more easily. Also, you could even make it a submodule.

**Comment by vinkla** [comment]
Yeah, thats true. Though, I don't want everything in it. Just almost :)
